name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Debug - Check Directory Structure
        run: ls -R

      - name: Debug - Verify package.json Location
        run: ls -l Chat-application/backend/package.json  # ✅ Corrected path

      - name: Install dependencies
        run: npm install
        working-directory: Chat-application/backend  # ✅ Corrected path

      - name: Run tests
        run: npm test
        working-directory: Chat-application/backend  # ✅ Corrected path
