name: CI Pipeline

on:
  push:
    branches:
      - main  # Runs on push to main branch
  pull_request:
    branches:
      - main  # Runs on PRs to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Adjust based on your project

      - name: Install Dependencies
        run: npm install

      - name: Lint Code
        run: npm run lint  # Assumes you have ESLint set up (optional)

      - name: Run Tests
        run: npm test  # Assumes you have tests (optional)

      - name: Start Application
        run: node server.js  # Adjust to your entry file
